---

name: CI
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'deekayen.splunk_enterprise'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4.1.0
        with:
          path: 'deekayen.splunk_enterprise'

      - name: Install test dependencies.
        run: python -m pip install --user ansible ansible-lint

      - name: Lint ansible.
        run: ansible-lint
